"""Backend-owned semantic layer (Task 16).

Houses the universal-hybrid evidence pipeline's semantic building blocks:

- `ontology/`   — a static, versioned, machine-readable IFC schema ontology and
  its committed BGE-M3 semantic index (backend-owned resource, read at runtime).
- `vocabulary/` — a bounded, read-only, model-specific semantic vocabulary
  derived from the live database and cached in memory per source model.
- `resolution.py` — threshold-free pre-planner semantic resolution over both.

Nothing in this package writes BIM tables, stored corpus vectors, source IFCs,
or viewer artifacts, and nothing imports the ingestion project or IfcOpenShell
at backend runtime (the ontology JSON/index are generated by an offline dev
utility and only *read* here).
"""
