/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query */
        post: operations["query_api_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Models
         * @description Deterministic bounded model list for the display-name selector.
         */
        get: operations["list_models_api_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/{source_model_id}/viewer-asset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Viewer Asset
         * @description Stream the prepared viewer artifact for an existing model (spec_v006 §9.3).
         *
         *     Verifies model existence, derives + contains the expected path, distinguishes
         *     missing/stale/unavailable with bounded responses, streams (never loads the
         *     whole file into memory), and supports fingerprint ETag / conditional GET.
         *     Never returns a server path in body, headers, or errors.
         */
        get: operations["viewer_asset_api_models__source_model_id__viewer_asset_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/{source_model_id}/entities/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve Entities
         * @description Active-model-scoped GlobalId -> compact identity (spec_v006 §10.3).
         */
        post: operations["resolve_entities_api_models__source_model_id__entities_resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnswerBasis
         * @description spec_v002 Section 13.
         * @enum {string}
         */
        AnswerBasis: "exact_sql" | "semantic_retrieval" | "graph_traversal" | "hybrid_evidence" | "general_knowledge" | "insufficient_evidence";
        /**
         * ContextEntityResult
         * @description A relationship-context entity (spec_v002 Section 10: distinguish from primary).
         */
        ContextEntityResult: {
            /** Entity Id */
            entity_id: number;
            /** Global Id */
            global_id: string;
            /** Ifc Class */
            ifc_class: string;
            /** Name */
            name?: string | null;
            /** Summary */
            summary?: string | null;
        };
        /**
         * EvidenceSummary
         * @description spec_v002 Section 13 — internal basis classification, bounded evidence counts.
         */
        EvidenceSummary: {
            basis: components["schemas"]["AnswerBasis"];
            /** Sql Match Count */
            sql_match_count?: number | null;
            /** Rag Candidate Count */
            rag_candidate_count?: number | null;
            /** Relationship Count */
            relationship_count?: number | null;
            /** Notes */
            notes?: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryTurn */
        HistoryTurn: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
        };
        /**
         * ModelAction
         * @enum {string}
         */
        ModelAction: "keep_current" | "await_user_confirmation" | "load_model";
        /**
         * ModelCandidate
         * @description spec_v002 Section 5 — a catalog model card, not an auto-loaded model.
         */
        ModelCandidate: {
            /** Source Model Id */
            source_model_id: number;
            /** Display Name */
            display_name?: string | null;
            /** Version Label */
            version_label?: string | null;
            /** Is Current */
            is_current?: boolean | null;
            status?: components["schemas"]["ModelStatus"] | null;
            /** Tags */
            tags?: string[];
        };
        /**
         * ModelListItem
         * @description One entry in the deterministic model selector (spec_v006 §10.1).
         */
        ModelListItem: {
            /** Source Model Id */
            source_model_id: number;
            /** Display Name */
            display_name: string;
            /** Source Fingerprint */
            source_fingerprint: string;
            viewer_asset_status: components["schemas"]["ViewerAssetStatus"];
        };
        /** ModelListResponse */
        ModelListResponse: {
            /** Models */
            models?: components["schemas"]["ModelListItem"][];
        };
        /**
         * ModelStatus
         * @description spec_v002 Section 5 — model availability/status.
         * @enum {string}
         */
        ModelStatus: "available" | "unavailable" | "processing";
        /**
         * PrimaryEntityResult
         * @description A primary-match entity. Compact summary only, not full canonical_json.
         */
        PrimaryEntityResult: {
            /** Entity Id */
            entity_id: number;
            /** Global Id */
            global_id: string;
            /** Ifc Class */
            ifc_class: string;
            /** Name */
            name?: string | null;
            /** Summary */
            summary?: string | null;
        };
        /**
         * QueryResponseEnvelope
         * @description spec_v002 Section 16.2 — the stable /api/query response shape.
         */
        QueryResponseEnvelope: {
            /** Request Id */
            request_id: string;
            /** Session Id */
            session_id: string;
            status: components["schemas"]["ResponseStatus"];
            scope: components["schemas"]["QueryScope"];
            route: components["schemas"]["QueryRoute"];
            answer_basis: components["schemas"]["AnswerBasis"];
            /** Answer */
            answer: string;
            /** Active Source Model Id */
            active_source_model_id?: number | null;
            /** Model Candidates */
            model_candidates?: components["schemas"]["ModelCandidate"][];
            /** Primary Entities */
            primary_entities?: components["schemas"]["PrimaryEntityResult"][];
            /** Context Entities */
            context_entities?: components["schemas"]["ContextEntityResult"][];
            /** Relationships */
            relationships?: components["schemas"]["RelationshipResult"][];
            viewer_actions?: components["schemas"]["ViewerActions"];
            evidence_summary: components["schemas"]["EvidenceSummary"];
            /** Warnings */
            warnings?: string[];
        };
        /**
         * QueryRoute
         * @description spec_v002 Section 7.4.
         * @enum {string}
         */
        QueryRoute: "sql" | "rag" | "graph" | "hybrid" | "explain_general" | "clarify";
        /**
         * QueryScope
         * @description spec_v002 Section 4.
         * @enum {string}
         */
        QueryScope: "model_catalog" | "active_model";
        /** RelationshipResult */
        RelationshipResult: {
            /** Relationship Id */
            relationship_id: number;
            /** Global Id */
            global_id: string;
            /** Ifc Class */
            ifc_class: string;
            /** Name */
            name?: string | null;
        };
        /**
         * ResolveEntitiesRequest
         * @description Active-model-scoped GlobalId resolution request (spec_v006 §10.3).
         */
        ResolveEntitiesRequest: {
            /** Global Ids */
            global_ids: string[];
        };
        /** ResolveEntitiesResponse */
        ResolveEntitiesResponse: {
            /** Source Model Id */
            source_model_id: number;
            /** Resolved */
            resolved?: components["schemas"]["ResolvedEntity"][];
            /** Unresolved */
            unresolved?: string[];
        };
        /** ResolvedEntity */
        ResolvedEntity: {
            /** Entity Id */
            entity_id: number;
            /** Global Id */
            global_id: string;
            /** Ifc Class */
            ifc_class: string;
            /** Name */
            name?: string | null;
        };
        /**
         * ResponseStatus
         * @description spec_v002 Section 16.2 — top-level /api/query response status.
         * @enum {string}
         */
        ResponseStatus: "success" | "error";
        /** RoleGroup */
        RoleGroup: {
            role: components["schemas"]["ViewerRole"];
            /** Global Ids */
            global_ids?: string[];
        };
        /**
         * SelectionAction
         * @enum {string}
         */
        SelectionAction: "select_and_fit" | "select_only" | "clear" | "none";
        /** SessionQueryRequest */
        SessionQueryRequest: {
            /** Question */
            question: string;
            /** Session Id */
            session_id: string;
            /** Active Source Model Id */
            active_source_model_id?: number | null;
            /** Selected Global Ids */
            selected_global_ids?: string[];
            /** Selected Entity Ids */
            selected_entity_ids?: number[];
            /** History */
            history?: components["schemas"]["HistoryTurn"][];
            /**
             * Reset
             * @default false
             */
            reset?: boolean;
            /** Confirm Model Id */
            confirm_model_id?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ViewerActions */
        ViewerActions: {
            /** @default keep_current */
            model_action?: components["schemas"]["ModelAction"];
            /** @default none */
            selection_action?: components["schemas"]["SelectionAction"];
            /** Primary Global Ids */
            primary_global_ids?: string[];
            /** Context Global Ids */
            context_global_ids?: string[];
            /** Role Groups */
            role_groups?: components["schemas"]["RoleGroup"][];
            /** Load Model Id */
            load_model_id?: number | null;
            /** Viewer Source Location */
            viewer_source_location?: string | null;
        };
        /**
         * ViewerAssetStatus
         * @description spec_v006 §10.1 — prepared-viewer-artifact availability for a model.
         *
         *     READY: the expected fingerprint artifact exists under the configured root.
         *     MISSING: no artifact prepared yet (the expected state until Task 11 runs).
         *     STALE: an artifact exists for the model but not for the current fingerprint.
         *     UNAVAILABLE: the catalog marks the model unavailable, or the artifact root
         *     cannot be safely resolved. Never leaks a server path (Task 10 §2/§3).
         * @enum {string}
         */
        ViewerAssetStatus: "ready" | "missing" | "stale" | "unavailable";
        /**
         * ViewerRole
         * @enum {string}
         */
        ViewerRole: "primary_match" | "relationship_context";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    query_api_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionQueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponseEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_api_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelListResponse"];
                };
            };
        };
    };
    viewer_asset_api_models__source_model_id__viewer_asset_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_model_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_entities_api_models__source_model_id__entities_resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_model_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveEntitiesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolveEntitiesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
